#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

"""Generate the files of a software deployment GPO, without touching AD.

Everything here is pure: input is plain data, output is text. Writing to
LDAP and SYSVOL happens elsewhere, so this part can be tested offline and
against the reference GPO of the handover (tests/unit).

A deployment is one GPO with one scheduled task (Group Policy Preference,
computer context) per winget package. The task runs as NT AUTHORITY\\System
- "EXAMPLE\\System", as picked by the RSAT account dialog, fails on the
clients with 0x80070534.
"""

import base64
import datetime
import re
import uuid
from xml.sax.saxutils import escape, quoteattr

import wingetindex

# Client side extension GUIDs (MS-GPPREF): Preference CSE for scheduled
# tasks and the matching tool extension of the Group Policy editor.
CSE_SCHEDULED_TASKS = "{AADCED64-746C-4633-A97C-D61349046527}"
TOOL_SCHEDULED_TASKS = "{CAB54552-DEEA-4691-817E-ED4A4D1AFC72}"
NULL_GUID = "{00000000-0000-0000-0000-000000000000}"

WEEKDAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
MODES = ("upgrade", "install")
DELIVERIES = ("sysvol", "embedded")

# A hung installer (e.g. an EXE package that waits for a desktop) would
# block every later package through the mutex: stop runs after two hours.
DEFAULT_TIME_LIMIT = "PT2H"
# The script itself stops winget and its installer earlier (with a log
# entry); the task limit above stays as the last resort.
DEFAULT_INSTALL_TIMEOUT = 30
# "" = let winget choose (no scope in the manifest, or nothing better)
SCOPES = ("", "machine")
TIME_LIMIT_RE = re.compile(r"^PT(0S|[1-9][0-9]?H)$")

TASK_NAME_RE = re.compile(r"^[\w][\w .()+\-]{0,99}$")
TIME_RE = re.compile(r"^([01]\d|2[0-3]):([0-5]\d)$")
DATE_RE = re.compile(r"^\d{4}-\d{2}-\d{2}$")

GUID_RE = re.compile(r"\{[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}\}")


class GenError(ValueError):
    pass


# ---------------------------------------------------------------- script ---

SCRIPT_TEMPLATE = r"""# Generated by the NethServer module windeploy. Do not edit: changes are
# overwritten when the deployment is saved again.
$PackageId = '{package_id}'
$Mode = '{mode}'
$Scope = '{scope}'
$TimeoutMinutes = {timeout_minutes}
$LogPath = '{log_path}'
Start-Transcript -Path $LogPath -Append | Out-Null
# One winget at a time: tasks of several deployments may start together and
# concurrent source updates fail ("Failed in attempting to update the source").
$mutex = New-Object System.Threading.Mutex($false, 'Global\windeploy')
$locked = $false
try {{
    try {{ $locked = $mutex.WaitOne([TimeSpan]::FromMinutes(60)) }} catch [System.Threading.AbandonedMutexException] {{ $locked = $true }}
    if (-not $locked) {{ Write-Output 'another winget run did not finish within 60 minutes'; exit 1 }}
    # C:\Program Files\WindowsApps is readable for SYSTEM only; the winget of
    # the newest App Installer is picked by its version number.
    $winget = Resolve-Path "$env:ProgramFiles\WindowsApps\Microsoft.DesktopAppInstaller_*_x64__8wekyb3d8bbwe\winget.exe" -ErrorAction SilentlyContinue |
        Sort-Object {{ [version](($_.Path -split '_')[1]) }} |
        Select-Object -Last 1
    if (-not $winget) {{ Write-Output 'winget.exe not found'; exit 1 }}
    Write-Output "winget: $($winget.Path)"
    # Package dependencies are only wired up for signed-in users: as SYSTEM
    # winget.exe fails with 0xC0000135 (DLL not found) unless the VC++
    # runtime is on the search path. Take the one of the newest VCLibs
    # package (not needed when the VC++ redistributable is installed).
    $vclibs = Get-ChildItem "$env:ProgramFiles\WindowsApps" -Directory -Filter 'Microsoft.VCLibs.140.00.UWPDesktop_*_x64__8wekyb3d8bbwe' -ErrorAction SilentlyContinue |
        Sort-Object {{ [version](($_.Name -split '_')[1]) }} |
        Select-Object -Last 1
    if ($vclibs) {{ $env:Path = $vclibs.FullName + ';' + $env:Path }}
    $common = @('--id', $PackageId, '--exact', '--source', 'winget', '--silent',
                '--accept-source-agreements', '--accept-package-agreements', '--disable-interactivity')
    # As SYSTEM winget may pick a per-user installer, which installs into
    # the profile of SYSTEM or waits for a desktop: ask for the machine one.
    if ($Scope -eq 'machine') {{ $common += @('--scope', 'machine') }}
    $verb = 'upgrade'
    if ($Mode -eq 'install') {{
        & $winget.Path list --id $PackageId --exact --source winget --accept-source-agreements --disable-interactivity | Out-Null
        if ($LASTEXITCODE -ne 0) {{ $verb = 'install' }}
    }}
    Write-Output "winget $verb $PackageId"
    # A silent installer can still wait for input nobody sees: stop winget
    # and everything it started after $TimeoutMinutes, so the log gets a
    # result and the next package is not blocked by the mutex.
    $out = Join-Path $env:TEMP ('windeploy-' + [guid]::NewGuid().ToString() + '.out')
    $p = Start-Process -FilePath $winget.Path -ArgumentList (@($verb) + $common) -NoNewWindow -PassThru -RedirectStandardOutput $out
    $null = $p.Handle
    if ($p.WaitForExit($TimeoutMinutes * 60000)) {{
        $code = $p.ExitCode
    }} else {{
        Write-Output "no result after $TimeoutMinutes minutes, stopping winget and the installer"
        $tree = @($p.Id)
        for ($i = 0; $i -lt $tree.Count; $i++) {{
            $tree += @(Get-CimInstance Win32_Process -Filter "ParentProcessId=$($tree[$i])" | ForEach-Object {{ $_.ProcessId }})
        }}
        [array]::Reverse($tree)
        foreach ($id in $tree) {{
            $proc = Get-Process -Id $id -ErrorAction SilentlyContinue
            if ($proc) {{ Write-Output "stop $($proc.ProcessName) ($id)"; Stop-Process -Id $id -Force -ErrorAction SilentlyContinue }}
        }}
        $code = 1460
    }}
    Get-Content -Path $out -Encoding UTF8 -ErrorAction SilentlyContinue | Write-Output
    Remove-Item -Path $out -ErrorAction SilentlyContinue
    Write-Output "Exitcode: $code"
    # Nothing to do is not a failure of the task:
    #   0x8A150014 no installed package (upgrade of a package that is missing)
    #   0x8A15002B no applicable update (already current)
    if ($verb -eq 'upgrade' -and ($code -eq -1978335212 -or $code -eq -1978335189)) {{
        Write-Output 'nothing to upgrade'
        $code = 0
    }}
    exit $code
}} finally {{
    if ($locked) {{ $mutex.ReleaseMutex() }}
    Stop-Transcript | Out-Null
}}
"""


def safe_file_part(package_id):
    """File name part for a package identifier (no characters Windows or
    PowerShell treat specially)."""
    return re.sub(r"[^A-Za-z0-9.\-]", "_", package_id)


def default_log_path(package_id):
    return "C:\\Windows\\Temp\\windeploy-" + safe_file_part(package_id) + ".log"


def build_script(package_id, mode="upgrade", log_path=None, scope="", timeout_minutes=DEFAULT_INSTALL_TIMEOUT):
    """PowerShell script for one package. Returned as text with CRLF line
    endings; encode as UTF-8 with BOM (Windows PowerShell 5.1 reads BOM-less
    files as ANSI). scope "machine" makes winget take the machine-wide
    installer; timeout_minutes stops a hung winget run."""
    if not wingetindex.valid_package_id(package_id):
        raise GenError(f"invalid package identifier {package_id!r}")
    if mode not in MODES:
        raise GenError(f"invalid mode {mode!r}")
    if scope not in SCOPES:
        raise GenError(f"invalid scope {scope!r}")
    if not isinstance(timeout_minutes, int) or not 5 <= timeout_minutes <= 110:
        raise GenError("installer time limit must be between 5 and 110 minutes")
    log_path = log_path or default_log_path(package_id)
    if not re.match(r"^[A-Za-z]:\\[\w .\\\-]{1,200}\.log$", log_path) or ".." in log_path:
        raise GenError(f"invalid log path {log_path!r}")
    text = SCRIPT_TEMPLATE.format(package_id=package_id, mode=mode, log_path=log_path,
                                  scope=scope, timeout_minutes=timeout_minutes)
    return text.replace("\r\n", "\n").replace("\n", "\r\n")


def script_bytes(script_text):
    return b"\xef\xbb\xbf" + script_text.encode("utf-8")


def compact_script(script_text):
    """Script without comment lines and indentation, for -EncodedCommand
    (the task command line is limited to 32767 characters)."""
    lines = [ln.strip() for ln in script_text.splitlines()]
    return "\r\n".join(ln for ln in lines if ln and not ln.startswith("#")) + "\r\n"


def encoded_command(script_text):
    """-EncodedCommand value (base64 of UTF-16LE) of the compacted script."""
    return base64.b64encode(compact_script(script_text).encode("utf-16-le")).decode("ascii")


# ------------------------------------------------------------------ task ---

def _check_schedule(schedule):
    freq = schedule.get("frequency", "weekly")
    if freq not in ("daily", "weekly"):
        raise GenError(f"invalid frequency {freq!r}")
    if not TIME_RE.match(schedule.get("time", "")):
        raise GenError(f"invalid time {schedule.get('time')!r}")
    start = schedule.get("start_date", "")
    if not DATE_RE.match(start):
        raise GenError(f"invalid start date {start!r}")
    datetime.date.fromisoformat(start)
    days = schedule.get("days", [])
    if freq == "weekly":
        if not days or any(d not in WEEKDAYS for d in days):
            raise GenError(f"invalid weekdays {days!r}")
    delay = int(schedule.get("random_delay_minutes", 0))
    if not 0 <= delay <= 1440:
        raise GenError("random delay must be between 0 and 1440 minutes")
    return freq, days, delay


def _trigger(schedule):
    freq, days, delay = _check_schedule(schedule)
    start = f"{schedule['start_date']}T{schedule['time']}:00"
    parts = [f"<CalendarTrigger><StartBoundary>{start}</StartBoundary><Enabled>true</Enabled>"]
    if delay:
        parts.append(f"<RandomDelay>PT{delay}M</RandomDelay>")
    if freq == "daily":
        parts.append("<ScheduleByDay><DaysInterval>1</DaysInterval></ScheduleByDay>")
    else:
        ordered = [d for d in WEEKDAYS if d in days]
        parts.append("<ScheduleByWeek><WeeksInterval>1</WeeksInterval><DaysOfWeek>"
                     + "".join(f"<{d}/>" for d in ordered)
                     + "</DaysOfWeek></ScheduleByWeek>")
    parts.append("</CalendarTrigger>")
    return "".join(parts)


def task_arguments(delivery, script_unc=None, script_text=None):
    if delivery == "sysvol":
        if not script_unc or not script_unc.startswith("\\\\") or '"' in script_unc:
            raise GenError(f"invalid script path {script_unc!r}")
        return f'-NoProfile -ExecutionPolicy Bypass -File "{script_unc}"'
    if delivery == "embedded":
        return "-NoProfile -NonInteractive -ExecutionPolicy Bypass -EncodedCommand " + encoded_command(script_text)
    raise GenError(f"invalid delivery {delivery!r}")


def _time_limit(task):
    limit = task.get("time_limit", DEFAULT_TIME_LIMIT)
    if not TIME_LIMIT_RE.match(limit):
        raise GenError(f"invalid time limit {limit!r}")
    return limit


def build_task(task):
    """One <TaskV2> element. task keys: name, uid, changed (datetime),
    author, arguments, schedule."""
    name = task["name"]
    if not TASK_NAME_RE.match(name):
        raise GenError(f"invalid task name {name!r}")
    uid = task["uid"].upper()
    if not GUID_RE.fullmatch(uid):
        raise GenError(f"invalid task uid {uid!r}")
    changed = task["changed"].strftime("%Y-%m-%d %H:%M:%S")
    return (
        f'<TaskV2 clsid="{{D8896631-B747-47a7-84A6-C155337F3BC8}}" name={quoteattr(name)} image="2" '
        f'changed="{changed}" uid="{uid}">'
        f'<Properties action="U" name={quoteattr(name)} runAs="NT AUTHORITY\\System" logonType="S4U">'
        '<Task version="1.3">'
        f'<RegistrationInfo><Author>{escape(task.get("author", ""))}</Author><Description>{escape(task.get("description", ""))}</Description></RegistrationInfo>'
        '<Principals><Principal id="Author"><UserId>NT AUTHORITY\\System</UserId>'
        '<LogonType>S4U</LogonType><RunLevel>HighestAvailable</RunLevel></Principal></Principals>'
        '<Settings><IdleSettings><Duration>PT10M</Duration><WaitTimeout>PT1H</WaitTimeout>'
        '<StopOnIdleEnd>true</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle></IdleSettings>'
        '<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>'
        '<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>'
        '<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>'
        '<AllowHardTerminate>false</AllowHardTerminate>'
        '<StartWhenAvailable>true</StartWhenAvailable>'
        '<RunOnlyIfNetworkAvailable>false</RunOnlyIfNetworkAvailable>'
        '<AllowStartOnDemand>true</AllowStartOnDemand>'
        '<Enabled>true</Enabled><Hidden>false</Hidden><RunOnlyIfIdle>false</RunOnlyIfIdle>'
        f'<WakeToRun>false</WakeToRun><ExecutionTimeLimit>{_time_limit(task)}</ExecutionTimeLimit><Priority>7</Priority>'
        '</Settings>'
        f'<Triggers>{_trigger(task["schedule"])}</Triggers>'
        '<Actions Context="Author"><Exec><Command>powershell.exe</Command>'
        f'<Arguments>{escape(task["arguments"])}</Arguments></Exec></Actions>'
        '</Task></Properties></TaskV2>'
    )


def build_immediate_task(task):
    """One <ImmediateTaskV2>: runs once when the policy is applied and is
    deleted afterwards. The run-once filter id makes every computer run it
    a single time; a new id (a new "run now") runs it again."""
    name = task["name"]
    if not TASK_NAME_RE.match(name):
        raise GenError(f"invalid task name {name!r}")
    uid = task["uid"].upper()
    run_id = task["run_once_id"].upper()
    for g in (uid, run_id):
        if not GUID_RE.fullmatch(g):
            raise GenError(f"invalid GUID {g!r}")
    changed = task["changed"].strftime("%Y-%m-%d %H:%M:%S")
    return (
        f'<ImmediateTaskV2 clsid="{{9756B581-76EC-4169-9AFC-0CA8D43ADB5F}}" name={quoteattr(name)} image="0" '
        f'changed="{changed}" uid="{uid}" userContext="0" removePolicy="0">'
        f'<Properties action="C" name={quoteattr(name)} runAs="NT AUTHORITY\\System" logonType="S4U">'
        '<Task version="1.3">'
        f'<RegistrationInfo><Author>{escape(task.get("author", ""))}</Author><Description>{escape(task.get("description", ""))}</Description></RegistrationInfo>'
        '<Principals><Principal id="Author"><UserId>NT AUTHORITY\\System</UserId>'
        '<LogonType>S4U</LogonType><RunLevel>HighestAvailable</RunLevel></Principal></Principals>'
        '<Settings><IdleSettings><Duration>PT5M</Duration><WaitTimeout>PT1H</WaitTimeout>'
        '<StopOnIdleEnd>false</StopOnIdleEnd><RestartOnIdle>false</RestartOnIdle></IdleSettings>'
        '<MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>'
        '<DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>'
        '<StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>'
        '<AllowHardTerminate>false</AllowHardTerminate>'
        '<StartWhenAvailable>true</StartWhenAvailable>'
        '<AllowStartOnDemand>false</AllowStartOnDemand>'
        '<Enabled>true</Enabled><Hidden>false</Hidden>'
        '<DeleteExpiredTaskAfter>PT0S</DeleteExpiredTaskAfter>'
        f'<ExecutionTimeLimit>{_time_limit(task)}</ExecutionTimeLimit><Priority>7</Priority>'
        '</Settings>'
        '<Triggers><TimeTrigger><StartBoundary>%LocalTimeXmlEx%</StartBoundary>'
        '<EndBoundary>%LocalTimeXmlEx%</EndBoundary><Enabled>true</Enabled></TimeTrigger></Triggers>'
        '<Actions Context="Author"><Exec><Command>powershell.exe</Command>'
        f'<Arguments>{escape(task["arguments"])}</Arguments></Exec></Actions>'
        '</Task></Properties>'
        f'<Filters><FilterRunOnce hidden="1" not="0" bool="AND" id="{run_id}"/></Filters>'
        '</ImmediateTaskV2>'
    )


def build_scheduled_tasks_xml(tasks, immediate=()):
    """Complete ScheduledTasks.xml (UTF-8 text) for a list of scheduled
    tasks and optional run-once immediate tasks."""
    names = [t["name"] for t in list(tasks) + list(immediate)]
    if len(set(n.lower() for n in names)) != len(names):
        raise GenError("task names must be unique within a GPO")
    body = "".join(build_task(t) for t in tasks) + "".join(build_immediate_task(t) for t in immediate)
    return ('<?xml version="1.0" encoding="utf-8"?>\r\n'
            '<ScheduledTasks clsid="{CC63F200-7309-4ba0-B154-A71CD118DBCC}">'
            + body + "</ScheduledTasks>")


def new_uid():
    return "{" + str(uuid.uuid4()).upper() + "}"


# ------------------------------------------------------ LDAP attributes ---

def parse_extension_names(value):
    """'[{CSE}{TOOL}...][...]' -> {CSE: set(TOOL, ...)} (upper case)."""
    result = {}
    value = (value or "").strip()
    if not value:
        return result
    if not re.fullmatch(r"(\[(\{[0-9A-Fa-f-]{36}\})+\])+", value):
        raise GenError(f"unexpected extension names format: {value!r}")
    for group in re.findall(r"\[([^\]]*)\]", value):
        guids = [g.upper() for g in GUID_RE.findall(group)]
        result.setdefault(guids[0], set()).update(guids[1:])
    return result


def format_extension_names(mapping):
    """Inverse of parse_extension_names: groups sorted by CSE GUID, tool
    GUIDs sorted inside a group - the order the Group Policy editor writes
    (reference GPO of the handover)."""
    out = []
    for cse in sorted(mapping):
        out.append("[" + cse + "".join(sorted(mapping[cse])) + "]")
    return "".join(out)


def add_scheduled_tasks_extension(value):
    """Return gPCMachineExtensionNames with the scheduled task preference
    registered. The editor lists every tool extension under the null GUID as
    well; keep that."""
    mapping = parse_extension_names(value)
    mapping.setdefault(CSE_SCHEDULED_TASKS, set()).add(TOOL_SCHEDULED_TASKS)
    mapping.setdefault(NULL_GUID, set()).add(TOOL_SCHEDULED_TASKS)
    return format_extension_names(mapping)


def bump_machine_version(version_number):
    """versionNumber: user version in the upper 16 bit, computer version in
    the lower 16 bit. Increment the computer part; it wraps to 1, not 0
    (0 means "never changed" to the clients)."""
    version_number = int(version_number)
    if not 0 <= version_number <= 0xFFFFFFFF:
        raise GenError(f"versionNumber out of range: {version_number}")
    user = version_number >> 16
    machine = version_number & 0xFFFF
    machine = machine + 1 if machine < 0xFFFF else 1
    return (user << 16) | machine


def build_gpt_ini(version_number, display_name=None):
    """GPT.INI content, byte-identical to the reference GPO (CRLF, file
    name GPT.INI in upper case)."""
    lines = ["[General]", f"Version={int(version_number)}"]
    if display_name:
        lines.append(f"displayName={display_name}")
    return "\r\n".join(lines) + "\r\n"
