#!/usr/bin/env python3

#
# Copyright (C) 2026 tebbi
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys

import agent
import wdcommon
import wingetindex

request = json.load(sys.stdin)
try:
    results = wingetindex.search(wdcommon.state_dir(), request["query"], request.get("limit", 50))
except wingetindex.IndexError_ as ex:
    print(agent.SD_ERR + str(ex), file=sys.stderr)
    sys.exit(1)
json.dump({"packages": results, "index": wingetindex.read_meta(wdcommon.state_dir())}, fp=sys.stdout)
